### ISSUE TITLE
Import has problems with Cyrillic alphabet

### ISSUE THREAD

**Issue by srasthofer** [secure-software-engineering/CodeInspect#123] opened 2015-04-24 21:35 UTC
Seems that codeinspect has some problems with apps like: v2_ru.budist_1_58_Будист — социальный будильник.apk

**Comment by MarcMil** [comment] 2015-04-25 10:18
Could reproduce this issue now. The problem was due to the breving character й, which is different from the project's name, where the character is represented as the breving character and a "m".

Should be fixed now.

**Closed by MarcMil** 2015-04-25 10:18 UTC
Labels: bug

**Comment by srasthofer** [comment] 2015-04-25 11:23
Thx
