### ISSUE TITLE
Possible to debug apk without repackaging it?

### ISSUE THREAD

**Issue by flankerhqd** [secure-software-engineering/CodeInspect#126] opened 2015-05-04 09:50 UTC
Currently codeinspect need to repackage and resign the apk, which will break some targets' self sign-check. Anyway to debug an existing apk on a debuggable-set phone, without repackaging the target?

As the phone is set with debuggable (ro.debuggable=1, ro.secure=0) there is no need to set  debuggable=true in AndroidManifest.

**Comment by MarcMil** [comment] 2015-05-04 11:10
The problem is, that there is no line number information in the original apk, thus debugging wouldn't be much fun. Therefore, this is sadly currently out of scope.

**Comment by flankerhqd** [comment] 2015-05-05 15:11
Thanks MarcMil for your explaintation. So if I understand and observed correctly, codeinspect's repacking maps jimple line number onto corresponding dalvik instruction?

**Comment by MarcMil** [comment] 2015-05-05 15:17
Yes, that's true.

**Closed** 2015-05-11 06:57 UTC
