### ISSUE TITLE
Display byte constants in the form 0x00 ... 0xff instead of -127 ... 128

### ISSUE THREAD

**Issue by JanSteffan** [secure-software-engineering/CodeInspect#65] opened 2015-02-20 14:47 UTC
The current form of byte constants is uncommon and therefore hard to interpret: 

```
$r4 = newarray (byte)[32];
$r4[0] = 117;
$r4[1] = 89;
$r4[2] = -27;
$r4[3] = -43;
$r4[4] = 90;
```

**Comment by StevenArzt** [comment] 2015-02-20 14:58
This is a duplicate of https://github.com/secure-software-engineering/CodeInspect/issues/63

**Comment by MarcMil** [comment] 2015-02-24 10:46
According to the title, these two requests are not identical; Jan wants the hex representation for byte-array constants.
Steven, do you think we should use hex as default for byte constants? The downside is that Java uses -127 till 128 as well.

**Comment by StevenArzt** [comment] 2015-02-24 11:00
Can we make this a setting so that users can define how thy want constant arrays to be represented? Ideally, the language should support both and when importing an APK file, the tool should create the representation requested by the setting.

**Comment by MarcMil** [comment] 2015-02-24 11:48
Has been added to the options of the import wizard.

**Closed by MarcMil** 2015-02-24 11:48 UTC

**Comment by srasthofer** [comment] 2015-02-24 11:52
Guys, be careful with adding "options". I do not want a tool that has 100000000000 options and NOBODY understands whats going on
