### ISSUE TITLE
unmodified, working apps fail after import->Debug As Android App

### ISSUE THREAD

**Issue by markuzSchmidt** [secure-software-engineering/CodeInspect#84] opened 2015-03-11 17:54 UTC
I imported AdobeReader and DBnavigator "as Jimple" and tried to run it on emulator using "Debug As"->"Android App". Both apk's run perfectly fine on my emulator, if i install them directly via adb install, and as far as i know, importing into CodeInspect and shouldnt change anything.
For AdobeReader i got the following error while debugging:
```
com.adobe.reader: FATAL EXCEPTION: main
com.adobe.reader: Process: com.adobe.reader, PID: 1973
com.adobe.reader: java.lang.IllegalAccessError: Illegal class access ('com.adobe.reader.viewer.ARSplitPaneActivity' attempting to access 'android.support.v7.app.ActionBar$Callback') in attempt to invoke interface method android.support.v4.app.FragmentManager android.support.v7.app.ActionBar$Callback.getSupportFragmentManager() (declaration of 'com.adobe.reader.viewer.ARSplitPaneActivity' appears in /data/app/com.adobe.reader-1/base.apk)
com.adobe.reader: 	at com.adobe.reader.viewer.ARSplitPaneActivity.onCreate(ARSplitPaneActivity.jimple:1215)
com.adobe.reader: 	at android.app.Activity.performCreate(Activity.java:5933)
com.adobe.reader: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
com.adobe.reader: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
com.adobe.reader: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
com.adobe.reader: 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
com.adobe.reader: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
com.adobe.reader: 	at android.os.Handler.dispatchMessage(Handler.java:102)
com.adobe.reader: 	at android.os.Looper.loop(Looper.java:135)
com.adobe.reader: 	at android.app.ActivityThread.main(ActivityThread.java:5221)
com.adobe.reader: 	at java.lang.reflect.Method.invoke(Native Method)
com.adobe.reader: 	at java.lang.reflect.Method.invoke(Method.java:372)
com.adobe.reader: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
com.adobe.reader: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```
I got this kind of error (IllegalAccessError) for mulitple APKs, so AdobeReader is just an example for this behaviour.

For DBnavigator i got the following:
```
de.hafas.android.db: FATAL EXCEPTION: Thread-162
de.hafas.android.db: Process: de.hafas.android.db, PID: 1245
de.hafas.android.db: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to get length of null array
de.hafas.android.db: 	at de.hafas.a.eg.a(eg.jimple:639)
de.hafas.android.db: 	at de.hafas.a.eg.a(eg.jimple:550)
de.hafas.android.db: 	at de.hafas.main.HafasApp.onAppStart(HafasApp.jimple:175)
de.hafas.android.db: 	at de.hafas.a.bn.run(bn.jimple:150)
de.hafas.android.db: 	at java.lang.Thread.run(Thread.java:818)
```

I tried multiple emulator settings including ARM and x86, but the result didnt change.
Since i didnt get it to run for any of the apks i tested and there is no other issue regarding this fundamental problem here, there is still the possibilty i did a mistake while setting up CodeInspect. Or maybe it is just because of the windows_64 version i'm using?!

**Comment by MarcMil** [comment] 2015-03-12 13:06
Thanks for your report.
I have looked at your second issue:
It seems that the app is trying to access the version name:
$PackageInfo.<android.content.pm.PackageInfo: java.lang.String versionName>
which is not decoded by apktool to the Android Manifest, thus it is null at runtime.
apktool saves it to a corresponding yml file. Interesting.

I will inform you when this one is fixed. I will look on your other issue afterwards.

**Comment by MarcMil** [comment] 2015-03-12 23:49
Both issues should be fixed in the new nightly build.
The fix should also concern the IllegalAccessErrors you were seeing other APKs; if not, please tell us.

**Comment by markuzSchmidt** [comment] 2015-03-13 16:59
DBnavigator is working fine for me now.

The apk's concerning the first issue (for example AdobeReader) now produce another error. When starting "Debug" on emulator it loads and installs the apk correctly but seems to fail to start the debugger. Emulator sometimes shows a message like "waiting for debug" (it disappears very fast, so i couldnt read the complete message) while CodeInspects shows an empty error-dialog where im only able to press "Ok". After that the emulator returns to its previous state and CodeInspect stops any processing (like execution was terminated).

**Comment by MarcMil** [comment] 2015-04-05 15:51
Sadly I am unable to reproduce this. If you encounter this error again, it may help to start CodeInspect with the option -consolelog in order to produce stacktraces on the console.

**Comment by StevenArzt** [comment] 2015-11-12 15:23
Since there hasn't been much activity on this issue for a while now and the problem cannot be reproduced anymore, I close the report.

**Closed by StevenArzt** 2015-11-12 15:23 UTC
